# Generated by Django 5.1.1 on 2024-12-09 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animal_records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_condtion', models.CharField(choices=[('healthy', 'Healthy'), ('sick', 'Sick'), ('undertreatment', 'Undertreatment')], max_length=255)),
                ('diagnosed_illness', models.TextField(blank=True, null=True)),
                ('vaccination_history', models.TextField(blank=True, null=True)),
                ('veterinary_visits', models.TextField(blank=True, null=True)),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('recovery_status', models.CharField(choices=[('improving', 'Improving'), ('stable', 'Stable'), ('worsening', 'Worsening')], max_length=255)),
                ('treatment_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='animal_records.animalrecords')),
            ],
        ),
    ]
