# Generated by Django 4.1.13 on 2025-01-20 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0002_rename_cow_healthrecord_cow_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthrecord',
            old_name='cow_name',
            new_name='name',
        ),
    ]
