# Generated by Django 4.1.13 on 2025-01-20 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0003_rename_cow_name_healthrecord_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthrecord',
            old_name='name',
            new_name='cow',
        ),
    ]
