# Generated by Django 4.1.13 on 2025-01-22 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0004_rename_name_healthrecord_cow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthrecord',
            old_name='health_condtion',
            new_name='health_condition',
        ),
    ]
