# Generated by Django 4.1.13 on 2025-01-24 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal_records', '0002_remove_animalrecords_cow_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalrecords',
            name='monthly_milk_yield',
        ),
    ]
