# Generated by Django 4.1.13 on 2025-02-03 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal_records', '0003_remove_animalrecords_monthly_milk_yield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animalrecords',
            old_name='name',
            new_name='cow_name',
        ),
        migrations.RemoveField(
            model_name='animalrecords',
            name='daily_milk_yield',
        ),
    ]
