# Generated by Django 4.1.13 on 2025-02-03 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal_records', '0004_rename_name_animalrecords_cow_name_and_more'),
    ]

    operations = [
    ]
