# Generated by Django 4.1.13 on 2025-02-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_records', '0005_auto_20250203_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalrecords',
            name='cow_name',
            field=models.CharField(default='Unnamed Cow', max_length=255),
            preserve_default=False,
        ),
    ]
