# Generated by Django 5.1.1 on 2025-01-16 05:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_records', '0002_remove_animalrecords_cow_id'),
        ('farm_finance', '0001_initial'),
        ('health_records', '0001_initial'),
        ('milk_records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='FarmFinanceSummary',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='expense_date',
        ),
        migrations.RemoveField(
            model_name='income',
            name='sale_date',
        ),
        migrations.RemoveField(
            model_name='income',
            name='source',
        ),
        migrations.AddField(
            model_name='expense',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animal_expense_entries', to='animal_records.animalrecords'),
        ),
        migrations.AddField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('FEED', 'Feed Purchase'), ('VET', 'Veterinary Services'), ('LABOR', 'Labor Costs'), ('EQUIPMENT', 'Equipment'), ('MAINTENANCE', 'Maintenance'), ('OTHER', 'Other Expenses')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='health_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_expense_entries', to='health_records.healthrecord'),
        ),
        migrations.AddField(
            model_name='expense',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='income',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animal_income_entries', to='animal_records.animalrecords'),
        ),
        migrations.AddField(
            model_name='income',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='income',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='income',
            name='description',
            field=models.CharField(default=11, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='income_type',
            field=models.CharField(choices=[('MILK', 'Milk Sales'), ('CATTLE', 'Cattle Sales'), ('MANURE', 'Manure Sales'), ('OTHER', 'Other Income')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='income',
            name='milk_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milk_income_entries', to='milk_records.milkrecord'),
        ),
        migrations.AddField(
            model_name='income',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
