# Generated by Django 5.1.1 on 2025-01-16 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm_finance', '0002_delete_farmfinancesummary_remove_expense_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='income',
            name='created_by',
        ),
    ]
