# Generated by Django 4.1.13 on 2025-01-21 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm_finance', '0004_expense_created_by_income_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='animal',
            new_name='animal_record',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='animal',
            new_name='animal_record',
        ),
    ]
