# Generated by Django 4.1.13 on 2025-01-21 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm_finance', '0005_rename_animal_expense_animal_record_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='reference_number',
        ),
        migrations.RemoveField(
            model_name='income',
            name='reference_number',
        ),
    ]
