# Generated by Django 4.1.13 on 2025-01-21 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm_finance', '0006_remove_expense_reference_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='animal_record',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='health_record',
        ),
        migrations.RemoveField(
            model_name='income',
            name='animal_record',
        ),
        migrations.RemoveField(
            model_name='income',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='income',
            name='description',
        ),
        migrations.RemoveField(
            model_name='income',
            name='milk_record',
        ),
    ]
