# Generated by Django 4.1.13 on 2025-01-21 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm_finance', '0007_remove_expense_animal_record_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='description',
        ),
    ]
