# Generated by Django 4.1.13 on 2025-01-22 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm_finance', '0009_annualfinance_quarterlyfinance_monthlyfinance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnnualFinance',
        ),
        migrations.DeleteModel(
            name='MonthlyFinance',
        ),
        migrations.DeleteModel(
            name='QuarterlyFinance',
        ),
    ]
