# Generated by Django 5.1.1 on 2025-01-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('report_type', models.CharField(max_length=50)),
                ('data', models.JSONField()),
            ],
            options={
                'get_latest_by': 'generated_date',
                'indexes': [models.Index(fields=['generated_date', 'report_type'], name='analytics_a_generat_2d45e1_idx')],
            },
        ),
    ]
