# Generated by Django 4.1.13 on 2025-02-04 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal_records', '0006_alter_animalrecords_cow_name'),
        ('analytics_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkYieldPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_yield', models.FloatField()),
                ('prediction_date', models.DateField(auto_now_add=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal_records.animalrecords')),
            ],
        ),
        migrations.DeleteModel(
            name='AnalyticsReport',
        ),
    ]
