# Generated by Django 5.1.1 on 2024-12-08 16:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animal_records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milking_date', models.DateField(default=datetime.date.today)),
                ('morning_milk_quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('afternoon_milk_quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('evening_milk_quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_records', to='animal_records.animalrecords')),
            ],
        ),
    ]
